{ ... }:
{
  # Hardware configuration usually generated by nixos-generate-config
  # You should populate this with your actual hardware config
  fileSystems."/" = { device = "/dev/disk/by-label/nixos"; fsType = "ext4"; };
  boot.loader.grub.device = "/dev/sda"; # Placeholder
}
